baseURL = 'https://azaleas.imprecision.art/'
locale = 'en-us'
title = 'The Azaleas Project'
uglyURLs = true

[menus]
[[menus.main]]
  url = "https://imprecision.art/"
  weight = 100
  name = "Imprecision"

[params]
  showAuthor = true
  colorScheme = 'magenta'
  description = "Translations of 진달래꽃 ('Azaleas') by Kim Sowol prepared for the September 17, 2026 Unpoetry at the Frye performance."

[params.author]
  name = "Kim Sowol"

[module]
  [[module.imports]]
    path = 'github.com/sergeyklay/gohugo-theme-ed'

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["txt"]

[outputFormats]
  [outputFormats.html]
  noUgly = true

  [outputFormats.plaintext]
    mediaType = "text/plain"
    path = "txt"

[outputs]
  home = ["HTML"]
  page = ["HTML", "plaintext"]
