baseURL = 'https://azaleas.imprecision.art/'
locale = 'en-us'
title = 'The Azaleas Project'

[menus]
[[menus.main]]
  url = "https://imprecision.art/"
  weight = 100
  name = "Imprecision"

[params]
  showAuthor = true
  colorScheme = 'magenta'

[params.author]
  name = "Kim Sowol"

[module]
  [[module.imports]]
    path = 'github.com/sergeyklay/gohugo-theme-ed'